### ISSUE TITLE
waveshare display

### ISSUE THREAD

**Issue by HDuc1889** [leonrinkel/nRF52-eink-epaper#2]
Hi Leonrinkel,

I am learning about communication from nrf52832 to waveshare display.
So, what is the version of SDK library that you are using. And, what I must change in your code if I would like to work thi the 2.7" waveshare display.
Many thanks in advance.

Best regards,

**Comment by leonrinkel** [comment]
Hi, I can't remember what SDK version I used. Waveshare provides Arduino example code for all of their displays. I'd start by looking at the 2.7" example code. Obviously there will be other values for width and height, but there may other differences like command values or lookup-tables. The other stuff like spi should be the same.
